In [1]:
import numpy as np

In [27]:
A = np.array([[1,4,3],[6,5,0],[1,9,0]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [28]:
A+B*A+B*A+B

array([[28, 76, 52],
       [84, 60,  4],
       [10, 47,  1]])

In [29]:
A-B*A-B*A-B

array([[-26, -68, -46],
       [-72, -50,  -4],
       [ -8, -29,  -1]])

In [30]:
A.T

array([[1, 6, 1],
       [4, 5, 9],
       [3, 0, 0]])

In [31]:
np.linalg.det(A)

np.float64(146.99999999999997)

In [32]:
A_INV=np.linalg.inv(A)

In [33]:
A_INV

array([[ 0.        ,  0.18367347, -0.10204082],
       [ 0.        , -0.02040816,  0.12244898],
       [ 0.33333333, -0.03401361, -0.1292517 ]])

In [34]:
A@A_INV

array([[ 1.00000000e+00, -6.93889390e-18,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [35]:
#we see form the above code that the result is the identity matrix

In [36]:
v= [1,2,3]

In [37]:
A@v

array([18, 16, 19])

In [ ]:
#the result vector has different length than the original one, it also points to
#a different direction due to the rotation done by the matrix A